---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

### Project overview

This is a guide for anyone who wants to analyze CyTOF data.The target audiences I have in mind are:

* Those that have looked at [my results](http://www.jimmunol.org/content/early/2018/08/15/jimmunol.1800716) and want to see how I analyzed the data
* Scientists with their own data that they would like to analyze
* Data scientists/ bioinformaticians looking to understand how to analyze
CyTOF data for a collaborator or project they are on

The goals of this guide are to provide you with all the information you need to 
analyze CyTOF data. I do this by going through in detail how I analyzed
a CyTOF data set that I generated. For more information on type of data
that CyTOF generates see [here](https://en.wikipedia.org/wiki/Mass_cytometry).

** Key findings: **

* A novel subset of memory T cells in human lymph nodes
* A new computational method to analyze CyTOF data of human T cells
* Evidence for tissue-specific features of memory T cells in healthy individuals
* Increased proliferation and cytotoxic function of memory CD8+ T cells in human lymph nodes


### Data overview

The data comes from a mass cytometer (CyTOF). CyTOF allows you to look at 
expression of many different proteins on single cells. The raw data is
mean expression of individual proteins on each individual cell.
CyTOF data is collected and saved in format of an .fcs file (Flow Cytometry
Standard format). This is a file format specific to flow cytometry and can be 
read by various flow cytometry softwares. Upon exporting the data from a flow cytometry 
software, more analysis can be done which is what I have done here. 

### Study Design

This data was collected by staining lymphocyte populations 
isolated from individiual human organ donor tissues with protein 
specific antibodies conjugated to isotopes that can be detected by CyTOF.

## Analyses

Here we present the reproducible the results of our analyses. They were 
generated by rendering the 
[R Markdown documents](https://github.com/davismcc/fibroblast-clonality/tree/master/analysis) 
into webpages available at the links below.

The results presented in the paper were produced with these analyses.

1. [Heatmaps of Protein Expression](Heatmap.html)
2. [Multidimensional Scaling of CyTOF data](MDS.html)
